uncategorized
_comment



	#InfOilNeedsRefactoring.

	"Se deben cambiar todas las implementaciones de los mÈtodos de esta clase que hacen referencia a clases de Oil Objects

	ya que a nivel de RBAC no se tendrÌa porquÈ tener conocimiento de las clases de Basic Oil Objects-Core.

	Por ahora lo solucionÈ moviendo dichos mÈtodos como loose methods del package Basic Oil Objects-Tests pero est· claro que esa no deberÌa ser

	la soluciÛn definitiva.

	Para saber cuales serÌan los mÈtodos a refactorizar, ver los looseMethods de clases de RBAC en el package Basic Oil Objects-Tests."